[build]
  command = "pnpm build"
  functions = "dist"
  publish = "dist/public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[env]
  [env.production]
    NODE_ENV = "production"
